export const bg = [
  {name: 'lightPink', hexcode: '#EF9A9A'},
  {name: 'darkPink', hexcode: '#F06292'},
  {name: 'purple', hexcode: '#BA68C8'},
  {name: 'lightPurple', hexcode: '#9575CD'},
  {name: 'blue', hexcode: '#2196F3'},
  {name: 'teal', hexcode: '#4DB6AC'},
  {name: 'green', hexcode: '#00C853'},
  {name: 'lime', hexcode: '#C0CA33'},
  {name: 'darkAmber', hexcode: '#FF6F00'},
  {name: 'orange', hexcode: '#FF9800'},
  {name: 'lightRed', hexcode: '#ef5350'},
  {name: 'deepPurple', hexcode: '#AB47BC'},
  {name: 'darkGreen', hexcode: '#388E3C'},
  {name: 'lightOrange', hexcode: '#FFA041'},
  {name: 'brightGreen', hexcode: '#00A90D'},
  {name: 'darkBlue', hexcode: '#009BCC'},
];
